create view CustomerwithGeography as
select [$Outer].[GeographyKey2] as [GeographyKey],
    [$Outer].[CustomerAlternateKey] as [CustomerAlternateKey],
    [$Outer].[Title] as [Title],
    [$Outer].[FirstName] as [FirstName],
    [$Outer].[MiddleName] as [MiddleName],
    [$Outer].[LastName] as [LastName],
    [$Outer].[NameStyle] as [NameStyle],
    [$Outer].[BirthDate] as [BirthDate],
    [$Outer].[MaritalStatus] as [MaritalStatus],
    [$Outer].[Suffix] as [Suffix],
    [$Outer].[Gender] as [Gender],
    [$Outer].[EmailAddress] as [EmailAddress],
    [$Outer].[YearlyIncome] as [YearlyIncome],
    [$Outer].[TotalChildren] as [TotalChildren],
    [$Outer].[NumberChildrenAtHome] as [NumberChildrenAtHome],
    [$Outer].[EnglishEducation] as [EnglishEducation],
    [$Outer].[SpanishEducation] as [SpanishEducation],
    [$Outer].[FrenchEducation] as [FrenchEducation],
    [$Outer].[EnglishOccupation] as [EnglishOccupation],
    [$Outer].[SpanishOccupation] as [SpanishOccupation],
    [$Outer].[FrenchOccupation] as [FrenchOccupation],
    [$Outer].[HouseOwnerFlag] as [HouseOwnerFlag],
    [$Outer].[NumberCarsOwned] as [NumberCarsOwned],
    [$Outer].[AddressLine1] as [AddressLine1],
    [$Outer].[AddressLine2] as [AddressLine2],
    [$Outer].[Phone] as [Phone],
    [$Outer].[DateFirstPurchase] as [DateFirstPurchase],
    [$Outer].[CommuteDistance] as [CommuteDistance],
    [$Inner].[City] as [DimGeography.1.City],
    [$Inner].[StateProvinceName] as [DimGeography.1.StateProvinceName]
from 
(
    select [GeographyKey] as [GeographyKey2],
        [CustomerAlternateKey] as [CustomerAlternateKey],
        [Title] as [Title],
        [FirstName] as [FirstName],
        [MiddleName] as [MiddleName],
        [LastName] as [LastName],
        [NameStyle] as [NameStyle],
        [BirthDate] as [BirthDate],
        [MaritalStatus] as [MaritalStatus],
        [Suffix] as [Suffix],
        [Gender] as [Gender],
        [EmailAddress] as [EmailAddress],
        [YearlyIncome] as [YearlyIncome],
        [TotalChildren] as [TotalChildren],
        [NumberChildrenAtHome] as [NumberChildrenAtHome],
        [EnglishEducation] as [EnglishEducation],
        [SpanishEducation] as [SpanishEducation],
        [FrenchEducation] as [FrenchEducation],
        [EnglishOccupation] as [EnglishOccupation],
        [SpanishOccupation] as [SpanishOccupation],
        [FrenchOccupation] as [FrenchOccupation],
        [HouseOwnerFlag] as [HouseOwnerFlag],
        [NumberCarsOwned] as [NumberCarsOwned],
        [AddressLine1] as [AddressLine1],
        [AddressLine2] as [AddressLine2],
        [Phone] as [Phone],
        [DateFirstPurchase] as [DateFirstPurchase],
        [CommuteDistance] as [CommuteDistance]
    from [dbo].[DimCustomer] as [$Table]
) as [$Outer]
left outer join [dbo].[DimGeography] as [$Inner] on ([$Outer].[GeographyKey2] = [$Inner].[GeographyKey])